---
title: "Visualization Markdown"
output: html_document
---

```{r}
# All code written by Evan Collins
# 14 February 2022, updated 12 February 2023
# Any questions can be sent to evantomcollins@gmail.com
```


```{r}
# Load packages
library(dplyr)
library(plotly)
library(readobj)
```

```{r}
# Load necessary files
load("files/vertex_number_by_parcel.rda")
load("files/parcel_names.rda")

atlas <- read.obj("files/atlas.obj")
# Necessary manipulations to match up labels/colors on appropriate hemispheres
atlas$shapes[[1]]$positions[1,][1:31868] <- -1*atlas$shapes[[1]]$positions[1,][1:31868]
atlas$shapes[[1]]$positions[1,][31869:length(atlas$shapes[[1]]$positions[1,])] <- -1*atlas$shapes[[1]]$positions[1,][31869:length(atlas$shapes[[1]]$positions[1,])]

atlas$shapes[[1]]$vertex_parcel_labels <- rep(parcel_names, vertex_number_by_parcel)

atlas_LH <- read.obj("files/atlas_LH.obj")
# Necessary manipulation to match up labels/colors on appropriate hemispheres
atlas_LH$shapes[[1]]$positions[1,] <- -1*atlas_LH$shapes[[1]]$positions[1,]

atlas_RH <- read.obj("files/atlas_RH.obj")
# Necessary manipulation to match up labels/colors on appropriate hemispheres
atlas_RH$shapes[[1]]$positions[1,] <- -1*atlas_RH$shapes[[1]]$positions[1,]

atlas_deep_LH <- read.obj("files/atlas_deep_LH.obj")
# Necessary manipulation to match up labels/colors on appropriate hemispheres
atlas_deep_LH$shapes[[1]]$positions[1,] <- -1*atlas_deep_LH$shapes[[1]]$positions[1,]

atlas_deep_RH <- read.obj("files/atlas_deep_RH.obj")
# Necessary manipulation to match up labels/colors on appropriate hemispheres
atlas_deep_RH$shapes[[1]]$positions[1,] <- -1*atlas_deep_RH$shapes[[1]]$positions[1,]

parcel_count_df <- read.csv("files/parcel_count.csv")
```

```{r}
# One example of how to compute RGB values for parcels
# Function to return list of RGB colors assigned to each parcel (i.e., their component vertices) with color intensity reflecting magnitude of input data column

# Input 1: dataframe = dataframe name with 696 rows corresponding to 696 parcels (first 348 should be left parcels; last 348 should be right parcels)
# Input 2: column = column name with by parcel frequency data
# Output: data_colors = list of three 696-length vectors with RGB colors for 696 parcels

# Note: If all values in provided column are positive, gradient will be white to red.
# Note: If all values in provided column are negative, gradient will be blue to white.
# Note: If values in provided column are negative and positive, gradient will be blue to white to red.

color_parcels_by_data <- function(dataframe, column){
  column_number <- which(colnames(dataframe) == column)
  data_colors_R <- col2rgb(ggplot_build(ggplot(dataframe, aes(x=as.numeric(dataframe[,column_number]), y=as.numeric(dataframe[,column_number]), color=as.numeric(dataframe[,column_number]))) + geom_point() + scale_color_gradientn(limits = c(-pmax(abs(min(as.numeric(dataframe[,column_number]))), abs(max(as.numeric(dataframe[,column_number])))), pmax(abs(min(as.numeric(dataframe[,column_number]))), abs(max(as.numeric(dataframe[,column_number]))))), colors = c("blue", "white", "red")))$data[[1]][[1]])[1,]
  data_colors_G <- col2rgb(ggplot_build(ggplot(dataframe, aes(x=as.numeric(dataframe[,column_number]), y=as.numeric(dataframe[,column_number]), color=as.numeric(dataframe[,column_number]))) + geom_point() + scale_color_gradientn(limits = c(-pmax(abs(min(as.numeric(dataframe[,column_number]))), abs(max(as.numeric(dataframe[,column_number])))), pmax(abs(min(as.numeric(dataframe[,column_number]))), abs(max(as.numeric(dataframe[,column_number]))))), colors = c("blue", "white", "red")))$data[[1]][[1]])[2,]
  data_colors_B <- col2rgb(ggplot_build(ggplot(dataframe, aes(x=as.numeric(dataframe[,column_number]), y=as.numeric(dataframe[,column_number]), color=as.numeric(dataframe[,column_number]))) + geom_point() + scale_color_gradientn(limits = c(-pmax(abs(min(as.numeric(dataframe[,column_number]))), abs(max(as.numeric(dataframe[,column_number])))), pmax(abs(min(as.numeric(dataframe[,column_number]))), abs(max(as.numeric(dataframe[,column_number]))))), colors = c("blue", "white", "red")))$data[[1]][[1]])[3,]
  data_colors <- list(data_colors_R, data_colors_G, data_colors_B)
  return(data_colors)
}
```

```{r}
# Get colors based on parcel counts cited in paper
freq_colors <- color_parcels_by_data(parcel_count_df, "freq")
```

```{r}
parcels_of_int_RH_names <- c("R_H_A", "R_H_B", "R_H_C", "R_A_A", "R_A_B", "R_I1_A", "R_I1_B", "R_I1_C", "R_I2_A", "R_I2_B", "R_I2_C", "R_I3_A", "R_I3_B", "R_I3_C", "R_I4_A", "R_I4_B", "R_I4_C", "R_I4_D", "R_I5_A", "R_I5_B", "R_I5_C", "R_I5_D")
parcels_of_int_LH_names <- gsub("R_", "L_", parcels_of_int_RH_names)

which(parcel_count_df$parcel %in% parcels_of_int_RH_names)
parcel_count_df$freq[which(parcel_count_df$parcel %in% parcels_of_int_RH_names)]
parcels_of_int_RH_freq <- parcel_count_df$freq[which(parcel_count_df$parcel %in% parcels_of_int_RH_names)]
```


```{r}
# Function to return list of 3D mesh Plotly figures for whole, LH, RH, deep LH, and deep RH parcellated brains.
# Input 1: atlas = whole brain atlas variable imported via read.obj
# Input 2: atlas_LH = LH brain atlas variable imported via read.obj
# Input 3: atlas_RH = RH brain atlas variable imported via read.obj
# Input 3: atlas_deep_LH = deep structures (amygdala, insula, hippocampus) of LH brain atlas variable imported via read.obj
# Input 4: atlas_deep_RH = deep structures (amygdala, insula, hippocampus) of RH brain atlas variable imported via read.obj
# Input 5: R_values = 696-length vector of R color values for 696 parcels (on RGB scale)
# Input 6: G_values = 696-length vector of G color values for 696 parcels (on RGB scale)
# Input 7: B_values = 696-length vector of B color values for 696 parcels (on RGB scale)
# Input 8: alpha_values = 696-length vector of alpha_values for 696 parcels
# Input 9: extra_text_values_df = 696-length vector of any additional information to be displayed in hovertext for 696 parcels 
# Output: plotly_atlas_whole_RH_LH_list = list of five 3D mesh Plotly figures for whole, LH, RH, deep LH, and deep RH parcellated brains

plot_plotly_atlas_whole_RH_LH <- function(atlas, atlas_LH, atlas_RH, atlas_deep_LH, atlas_deep_RH, R_values, G_values, B_values, alpha_values, extra_text_values){
  plotly_atlas_whole_RH_LH_list <- list()
  plotly_atlas_whole_RH_LH_list[[1]] <- plot_ly(type = "mesh3d",
                                                x = atlas$shapes[[1]]$positions[1,],
                                                y = atlas$shapes[[1]]$positions[3,],
                                                z = atlas$shapes[[1]]$positions[2,],
                                                vertexcolor = rep(rgb(R_values, G_values, B_values, alpha_values), vertex_number_by_parcel),
                                                i = atlas$shapes[[1]]$indices[1,],
                                                j = atlas$shapes[[1]]$indices[3,],
                                                k = atlas$shapes[[1]]$indices[2,],
                                                hovertext = paste0("Parcel: ", rep(parcel_names, vertex_number_by_parcel),
                                                                  "<br>Freq: ", rep(extra_text_values, vertex_number_by_parcel))) %>%
    layout(hoverlabel = list(bgcolor = "white", bordercolor = "darkblue", font = list(size = 15, family = "Verdana"))) %>%
    config(displaylogo = F, displayModeBar = F) %>%
    layout(scene = list(camera = list(eye = list(x = 1, y = 1, z = 0)))) #%>%
    #layout(paper_bgcolor = "rgb(68, 68, 68)", plot_bgcolor = "rgb(68, 68, 68)")
    
    
    plotly_atlas_whole_RH_LH_list[[2]] <- plot_ly(type = "mesh3d", 
                                                  x = atlas_LH$shapes[[1]]$positions[1,],
                                                  y = atlas_LH$shapes[[1]]$positions[3,],
                                                  z = atlas_LH$shapes[[1]]$positions[2,],
                                                  vertexcolor = rep(rgb(R_values, G_values, B_values, alpha_values), vertex_number_by_parcel)[1:31868],
                                                  opacity = 1,
                                                  i = atlas_LH$shapes[[1]]$indices[1,],
                                                  j = atlas_LH$shapes[[1]]$indices[3,],
                                                  k = atlas_LH$shapes[[1]]$indices[2,],
                                                  hovertext = paste0("Parcel: ", rep(parcel_names, vertex_number_by_parcel)[1:31868],
                                                                    "<br>Freq: ", rep(extra_text_values, vertex_number_by_parcel)[1:31868])) %>%
      layout(hoverlabel = list(bgcolor = "white", bordercolor = "darkblue", font = list(size = 15, family = "Verdana"))) %>%
      config(displaylogo = F, displayModeBar = F) %>%
      layout(scene = list(camera = list(eye = list(x = 1, y = 1, z = 0)))) #%>%
      #layout(paper_bgcolor = "rgb(68, 68, 68)", plot_bgcolor = "rgb(68, 68, 68)")
    
    plotly_atlas_whole_RH_LH_list[[3]] <- plot_ly(type = "mesh3d", 
                                                  x = atlas_RH$shapes[[1]]$positions[1,],
                                                  y = atlas_RH$shapes[[1]]$positions[3,],
                                                  z = atlas_RH$shapes[[1]]$positions[2,],
                                                  vertexcolor = rep(rgb(R_values, G_values, B_values, alpha_values), vertex_number_by_parcel)[31869:length(atlas$shapes[[1]]$vertex_parcel_labels)],
                                                  i = atlas_RH$shapes[[1]]$indices[1,],
                                                  j = atlas_RH$shapes[[1]]$indices[3,],
                                                  k = atlas_RH$shapes[[1]]$indices[2,],
                                                  hovertext = paste0("Parcel: ", rep(parcel_names, vertex_number_by_parcel)[31869:length(rep(parcel_names, vertex_number_by_parcel))],
                                                                    "<br>Freq: ", rep(extra_text_values, vertex_number_by_parcel)[31869:length(rep(parcel_names, vertex_number_by_parcel))])) %>%
      layout(hoverlabel = list(bgcolor = "white", bordercolor = "darkblue", font = list(size = 15, family = "Verdana"))) %>%
      config(displaylogo = F, displayModeBar = F) %>%
      layout(scene = list(camera = list(eye = list(x = 1, y = 1, z = 0)))) #%>%
      #layout(paper_bgcolor = "rgb(68, 68, 68)", plot_bgcolor = "rgb(68, 68, 68)")
    
    #############
    # Preparing data for deep structures
    parcels_of_int_RH_names <- c("R_H_A", "R_H_B", "R_H_C", "R_A_A", "R_A_B", "R_I1_A", "R_I1_B", "R_I1_C", "R_I2_A", "R_I2_B", "R_I2_C", "R_I3_A", "R_I3_B", "R_I3_C", "R_I4_A", "R_I4_B", "R_I4_C", "R_I4_D", "R_I5_A", "R_I5_B", "R_I5_C", "R_I5_D")
    parcels_of_int_LH_names <- gsub("R_", "L_", parcels_of_int_RH_names)
    parcels_of_int_RH <- which(parcel_names %in% parcels_of_int_RH_names)
    parcels_of_int_LH <- which(parcel_names %in% parcels_of_int_LH_names)
    colors_of_int_RH <- list()
    colors_of_int_LH <- list()
    for (i in 1:length(parcels_of_int_RH)){
      colors_of_int_RH[[i]] <- rep(rgb(R_values, G_values, B_values, 1), vertex_number_by_parcel)[(cumsum(vertex_number_by_parcel)[parcels_of_int_RH[i]-1]+1):(cumsum(vertex_number_by_parcel)[parcels_of_int_RH[i]])]
      colors_of_int_LH[[i]] <- rep(rgb(R_values, G_values, B_values, 1), vertex_number_by_parcel)[(cumsum(vertex_number_by_parcel)[parcels_of_int_LH[i]-1]+1):(cumsum(vertex_number_by_parcel)[parcels_of_int_LH[i]])]
    }
    vertex_number_by_parcel_of_int_RH <- vertex_number_by_parcel[parcels_of_int_RH]
    vertex_number_by_parcel_of_int_LH <- vertex_number_by_parcel[parcels_of_int_LH]
    colors_of_int_RH <- unlist(colors_of_int_RH)
    colors_of_int_LH <- unlist(colors_of_int_LH)
    #############
    
    plotly_atlas_whole_RH_LH_list[[4]] <- plot_ly(type = "mesh3d", 
                                                  x = atlas_deep_LH$shapes[[1]]$positions[1,],
                                                  y = atlas_deep_LH$shapes[[1]]$positions[3,],
                                                  z = atlas_deep_LH$shapes[[1]]$positions[2,],
                                                  vertexcolor = colors_of_int_LH,
                                                  i = atlas_deep_LH$shapes[[1]]$indices[1,],
                                                  j = atlas_deep_LH$shapes[[1]]$indices[3,],
                                                  k = atlas_deep_LH$shapes[[1]]$indices[2,],
                                                  hovertext = paste0("Parcel: ", rep(parcels_of_int_LH_names, vertex_number_by_parcel_of_int_LH),
                                                                    "<br>Freq: ", rep(extra_text_values[which(parcel_names %in% parcels_of_int_LH_names)], vertex_number_by_parcel_of_int_LH))) %>%
      layout(hoverlabel = list(bgcolor = "white", bordercolor = "darkblue", font = list(size = 15, family = "Verdana"))) %>%
      config(displaylogo = F, displayModeBar = F) %>%
      layout(scene = list(camera = list(eye = list(x = 1, y = 1, z = 0)))) #%>%
      #layout(paper_bgcolor = "rgb(68, 68, 68)", plot_bgcolor = "rgb(68, 68, 68)")
    
    plotly_atlas_whole_RH_LH_list[[5]] <- plot_ly(type = "mesh3d", 
                                                  x = atlas_deep_RH$shapes[[1]]$positions[1,],
                                                  y = atlas_deep_RH$shapes[[1]]$positions[3,],
                                                  z = atlas_deep_RH$shapes[[1]]$positions[2,],
                                                  vertexcolor = colors_of_int_RH,
                                                  i = atlas_deep_RH$shapes[[1]]$indices[1,],
                                                  j = atlas_deep_RH$shapes[[1]]$indices[3,],
                                                  k = atlas_deep_RH$shapes[[1]]$indices[2,],
                                                  hovertext = paste0("Parcel: ", rep(parcels_of_int_RH_names, vertex_number_by_parcel_of_int_RH),
                                                                    "<br>Freq: ", rep(extra_text_values[which(parcel_names %in% parcels_of_int_RH_names)], vertex_number_by_parcel_of_int_RH))) %>%
      layout(hoverlabel = list(bgcolor = "white", bordercolor = "darkblue", font = list(size = 15, family = "Verdana"))) %>%
      config(displaylogo = F, displayModeBar = F) %>%
      layout(scene = list(camera = list(eye = list(x = 1, y = 1, z = 0)))) #%>%
      #layout(paper_bgcolor = "rgb(68, 68, 68)", plot_bgcolor = "rgb(68, 68, 68)")
    
    return(plotly_atlas_whole_RH_LH_list)
}
```


# Visualizations

```{r}
# Whole Brain
# Note how we divide by 255 to have the upper bound of RGB values be 1
img1 <- plot_plotly_atlas_whole_RH_LH(atlas, atlas_LH, atlas_RH, atlas_deep_LH, atlas_deep_RH, freq_colors[[1]]/255, freq_colors[[2]]/255, freq_colors[[3]]/255, 1, parcel_count_df$freq)[[1]]
img1
```

```{r}
# LH
img2 <- plot_plotly_atlas_whole_RH_LH(atlas, atlas_LH, atlas_RH, atlas_deep_LH, atlas_deep_RH, freq_colors[[1]]/255, freq_colors[[2]]/255, freq_colors[[3]]/255, 1, parcel_count_df$freq)[[2]]
img2
```

```{r}
# RH
img3 <- plot_plotly_atlas_whole_RH_LH(atlas, atlas_LH, atlas_RH, atlas_deep_RH, atlas_deep_LH, freq_colors[[1]]/255, freq_colors[[2]]/255, freq_colors[[3]]/255, 1, parcel_count_df$freq)[[3]]
img3
```


```{r}
# deep LH
img4 <- plot_plotly_atlas_whole_RH_LH(atlas, atlas_LH, atlas_RH, atlas_deep_RH, atlas_deep_LH, freq_colors[[1]]/255, freq_colors[[2]]/255, freq_colors[[3]]/255, 1, parcel_count_df$freq)[[4]]
img4
```


```{r}
# deep RH
img5 <- plot_plotly_atlas_whole_RH_LH(atlas, atlas_LH, atlas_RH, atlas_deep_RH, atlas_deep_LH, freq_colors[[1]]/255, freq_colors[[2]]/255, freq_colors[[3]]/255, 1, parcel_count_df$freq)[[5]]
img5
```

